// The mod's own art. Vanilla assets come from the data.win extract (cache/assets); this
// loads what the mod itself ships so rooms can place and draw mod things:
//
//   <modDir>/Sprites/<name>_<N>.png   frame N of sprite <name> (0-based; bare <name>.png
//                                     is a single-frame sprite). MSL's packer gives these
//                                     origin (0,0) and a full-frame margin
//                                     (TextureLoader.cs:140-141) -- untrimmed PNGs.
//   <modDir>/assets.json              the manifest the editor owns: object registrations
//                                     (sprite/parent/visible/...) and per-sprite origin/
//                                     margin overrides. The same manifest is compiled to
//                                     <Mod>.Assets.g.cs (genAssetsCs), so what the editor
//                                     shows is what the game registers -- no C# parsing
//                                     anywhere. The .g.cs self-heals: whenever a scan sees
//                                     it disagree with the manifest, it is rewritten.
//
// Mod frames get pseudo page numbers starting at MOD_PAGE_BASE so the client's Frame
// tuple and texture pipeline work unchanged; /mod-assets/pages/<i>.png serves the file.
import fs from "node:fs";
import path from "node:path";
import { tr } from "../src/i18n/index.ts";
import { reqLang } from "./langctx.ts";

export const MOD_PAGE_BASE = 1_000_000;

// same shapes as src/assets.ts, redeclared so the server never pulls pixi.js
export type Frame = [number, number, number, number, number, number, number, number, number, number, number] | [];
export interface ModSpriteDef {
  w: number;
  h: number;
  ox: number;
  oy: number;
  margin: [number, number, number, number]; // [left, top, right, bottom], inclusive
  frames: Frame[];
}
export interface ModObjectDef {
  // sparse: only fields the manifest actually sets. A fixup overlays a vanilla object and
  // must not clobber the vanilla def's other fields with defaults.
  sprite?: string;
  parent?: string;
  visible?: boolean;
}

// ---------------- the manifest (assets.json) ----------------

export interface ManifestSprite {
  origin?: [number, number];
  margin?: [number, number, number, number]; // [left, top, right, bottom], inclusive
  note?: string;
}
export interface ManifestObject {
  sprite?: string;
  parent?: string;
  visible?: boolean;
  persistent?: boolean;
  awake?: boolean;
  collision?: string; // CollisionShapeFlags.<value>, e.g. "Box"
  note?: string;
}
export interface AssetsManifest {
  sprites: Record<string, ManifestSprite>;
  objects: Record<string, ManifestObject>;
}

export const manifestPath = (modDir: string) => path.join(modDir, "assets.json");
export const generatedCsPath = (modDir: string) => path.join(modDir, `${path.basename(modDir)}.Assets.g.cs`);

// whole-file rewrite; the manifest is editor-owned, so it also owns the formatting
export function saveManifest(modDir: string, manifest: AssetsManifest): void {
  fs.writeFileSync(manifestPath(modDir), JSON.stringify(manifest, null, 2) + "\n", "utf8");
}

export function loadManifest(modDir: string): { manifest: AssetsManifest; exists: boolean; warnings: string[] } {
  const p = manifestPath(modDir);
  const empty: AssetsManifest = { sprites: {}, objects: {} };
  if (!fs.existsSync(p)) return { manifest: empty, exists: false, warnings: [] };
  try {
    const raw = JSON.parse(fs.readFileSync(p, "utf8")) as Partial<AssetsManifest>;
    return { manifest: { sprites: raw.sprites ?? {}, objects: raw.objects ?? {} }, exists: true, warnings: [] };
  } catch (e) {
    return { manifest: empty, exists: true, warnings: [tr(reqLang(), "assets.json 解析失败：{msg}", { msg: (e as Error).message })] };
  }
}

// ---------------- codegen: assets.json -> <Mod>.Assets.g.cs ----------------

// Deterministic: same manifest in, same bytes out. Objects with only sprite/parent/visible
// use the property-assignment style; anything with more fields uses one named-arg call.
export function genAssetsCs(manifest: AssetsManifest, modName: string): string {
  const L: string[] = [
    "// GENERATED by stoneshard-room-editor from assets.json -- do not edit by hand.",
    "// The editor rewrites this file whenever it disagrees with assets.json (server start,",
    "// /api/mod-assets, doc compile), or on demand: python cli/svre.py assets sync",
    "using ModShardLauncher;",
    "using ModShardLauncher.Mods;",
    "using UndertaleModLib.Models;",
    "",
    `namespace ${modName};`,
    "",
    "public static class SvGeneratedAssets",
    "{",
    "    // Call before any AddRoomJson / AddNewEvent that references these names;",
    "    // RequireObjectInstances / RequireCreationCodes guard the order at build time.",
    "    public static void Register()",
    "    {",
  ];
  const ident = /^[A-Za-z_]\w*$/;
  for (const [name, o] of Object.entries(manifest.objects)) {
    if (o.note) L.push(`        // ${name}: ${o.note}`);
    const simple = o.persistent === undefined && o.awake === undefined && o.collision === undefined;
    if (simple && ident.test(name)) {
      L.push(`        UndertaleGameObject ${name} = Msl.AddObject("${name}");`);
      if (o.parent) L.push(`        ${name}.ParentId = Msl.GetObject("${o.parent}");`);
      if (o.sprite) L.push(`        ${name}.Sprite = Msl.GetSprite("${o.sprite}");`);
      if (o.visible !== undefined) L.push(`        ${name}.Visible = ${o.visible};`);
    } else {
      const args: string[] = [`"${name}"`];
      if (o.sprite) args.push(`spriteName: "${o.sprite}"`);
      if (o.parent) args.push(`parentName: "${o.parent}"`);
      if (o.visible !== undefined) args.push(`isVisible: ${o.visible}`);
      if (o.persistent !== undefined) args.push(`isPersistent: ${o.persistent}`);
      if (o.awake !== undefined) args.push(`isAwake: ${o.awake}`);
      if (o.collision) args.push(`collisionShapeFlags: CollisionShapeFlags.${o.collision}`);
      L.push(`        Msl.AddObject(${args.join(", ")});`);
    }
    L.push("");
  }
  for (const [name, s] of Object.entries(manifest.sprites)) {
    if (!s.origin && !s.margin) continue; // note-only entries exist just for the editor
    if (s.note) L.push(`        // ${name}: ${s.note}`);
    L.push(`        UndertaleSprite ${name} = Msl.GetSprite("${name}");`);
    if (s.origin) {
      L.push(`        ${name}.OriginX = ${s.origin[0]};`);
      L.push(`        ${name}.OriginY = ${s.origin[1]};`);
    }
    if (s.margin) {
      L.push(`        ${name}.MarginLeft = ${s.margin[0]};`);
      L.push(`        ${name}.MarginTop = ${s.margin[1]};`);
      L.push(`        ${name}.MarginRight = ${s.margin[2]};`);
      L.push(`        ${name}.MarginBottom = ${s.margin[3]};`);
    }
    L.push("");
  }
  while (L[L.length - 1] === "") L.pop();
  L.push("    }", "}", "");
  return L.join("\n");
}

// ---------------- the scan ----------------

export interface VanillaNames {
  objects: Set<string>;
  sprites: Set<string>;
}

export interface ModAssets {
  sprites: Record<string, ModSpriteDef>;
  objects: Record<string, ModObjectDef>;
  pages: string[]; // absolute paths; index i <-> pseudo page MOD_PAGE_BASE + i
  warnings: string[];
  synced: boolean; // the generated .g.cs was (re)written by this scan
}

export function pngSizeBuffer(buf: Buffer): { w: number; h: number } | null {
  if (buf.length < 26) return null;
  if (buf.readUInt32BE(0) !== 0x89504e47 || buf.toString("ascii", 12, 16) !== "IHDR") return null;
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}

function pngSize(file: string): { w: number; h: number } | null {
  const fd = fs.openSync(file, "r");
  try {
    const buf = Buffer.alloc(26);
    if (fs.readSync(fd, buf, 0, 26, 0) < 26) return null;
    if (buf.readUInt32BE(0) !== 0x89504e47 || buf.toString("ascii", 12, 16) !== "IHDR") return null;
    return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
  } finally {
    fs.closeSync(fd);
  }
}

// `write: false` makes the scan purely read-only: it still reports every warning, but
// skips the self-heal below. The diagnostics endpoint needs that -- a GET must not rewrite
// <Mod>.Assets.g.cs behind a client that is not re-reading the sprite pages.
export function scanModAssets(modDir: string, opts: { vanilla?: VanillaNames; write?: boolean } = {}): ModAssets {
  const pages: string[] = [];
  const sprites: Record<string, ModSpriteDef> = {};
  const objects: Record<string, ModObjectDef> = {};
  const warnings: string[] = [];

  // ---------------- Sprites/*.png ----------------
  const spritesDir = path.join(modDir, "Sprites");
  if (fs.existsSync(spritesDir)) {
    const bySprite = new Map<string, { n: number; file: string }[]>();
    for (const f of fs.readdirSync(spritesDir).filter((f) => f.toLowerCase().endsWith(".png")).sort()) {
      const m = /^(.*?)(?:_(\d+))?\.png$/i.exec(f)!;
      const list = bySprite.get(m[1]) ?? [];
      list.push({ n: m[2] !== undefined ? Number(m[2]) : 0, file: path.join(spritesDir, f) });
      bySprite.set(m[1], list);
    }
    for (const [name, frames] of bySprite) {
      const count = Math.max(...frames.map((f) => f.n)) + 1;
      const defs: Frame[] = Array.from({ length: count }, () => []);
      let w = 0, h = 0;
      for (const f of frames) {
        const size = pngSize(f.file);
        if (!size) continue;
        const page = MOD_PAGE_BASE + pages.length;
        pages.push(f.file);
        defs[f.n] = [page, 0, 0, size.w, size.h, 0, 0, size.w, size.h, size.w, size.h];
        w = Math.max(w, size.w);
        h = Math.max(h, size.h);
      }
      sprites[name] = { w, h, ox: 0, oy: 0, margin: [0, 0, w - 1, h - 1], frames: defs };
    }
  }

  // ---------------- assets.json ----------------
  const { manifest, exists, warnings: mw } = loadManifest(modDir);
  warnings.push(...mw);
  const { vanilla } = opts;

  for (const [name, s] of Object.entries(manifest.sprites)) {
    const def = sprites[name];
    if (!def) {
      warnings.push(tr(reqLang(), "assets.json: sprite {name} 没有对应的 Sprites/*.png", { name }));
      continue;
    }
    if (s.origin) [def.ox, def.oy] = s.origin;
    if (s.margin) def.margin = [...s.margin];
  }
  for (const [name, o] of Object.entries(manifest.objects)) {
    const def: ModObjectDef = {};
    if (o.sprite) def.sprite = o.sprite;
    if (o.parent) def.parent = o.parent;
    if (o.visible !== undefined) def.visible = o.visible;
    objects[name] = def;
    if (o.sprite && !sprites[o.sprite] && !vanilla?.sprites.has(o.sprite))
      warnings.push(tr(reqLang(), "assets.json: {name} 的 sprite {sprite} 既不是 mod PNG 也不是原版 sprite", { name, sprite: o.sprite }));
    if (o.parent && !manifest.objects[o.parent] && !vanilla?.objects.has(o.parent))
      warnings.push(tr(reqLang(), "assets.json: {name} 的 parent {parent} 不在原版对象表里", { name, parent: o.parent }));
    if (o.visible === undefined)
      warnings.push(tr(reqLang(), "assets.json: {name} 没写 visible（MSL 的 AddObject 默认 false，通常应为 true）", { name }));
  }

  // the generated C# self-heals: rewrite it whenever it disagrees with the manifest, so
  // what the editor shows and what the game registers can never drift apart
  let synced = false;
  if (exists && opts.write !== false) {
    const out = generatedCsPath(modDir);
    const text = genAssetsCs(manifest, path.basename(modDir));
    const cur = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : null;
    if (cur !== text) {
      try {
        fs.writeFileSync(out, text);
        synced = true;
      } catch (e) {
        warnings.push(tr(reqLang(), "生成 {out} 失败：{msg}", { out: path.basename(out), msg: (e as Error).message }));
      }
    }
  }

  return { sprites, objects, pages, warnings, synced };
}
