// rooms/*.compiled.json -> <Mod>.Rooms.g.cs: every compiled room becomes a const string
// in a generated, self-healing C# file, so the room JSON ships inside the mod's assembly
// instead of pretending to be a .gml file for ModFiles.GetCode.
//
// Why not a data file: the packer (ModShardPackerReference) only embeds Codes/*.gml and
// Sprites/*.png into the .sml, and its in-memory Roslyn compilation exposes no
// AdditionalFiles/EmbeddedResource entry point. A raw string literal (C# 11; the packer's
// Roslyn 4.7 accepts it) is the compile-time #include that actually exists here.
//
// The snapshots (rooms/<name>.compiled.json) are the editor-owned source for this file;
// it is REGENERATED WHOLESALE whenever it disagrees (server start, compile, import,
// adopt), so hand edits to it are simply overwritten -- like <Mod>.Assets.g.cs.
import fs from "node:fs";
import path from "node:path";

export const roomsCsPath = (modDir: string) => path.join(modDir, `${path.basename(modDir)}.Rooms.g.cs`);

// Legal JSON can never contain a run of bare `"` (tokens are separated by , : ] } or
// whitespace), so 3 is always enough -- but pick the delimiter defensively anyway.
function delimiterFor(text: string): string {
  let run = 0, max = 0;
  for (const ch of text) {
    run = ch === '"' ? run + 1 : 0;
    if (run > max) max = run;
  }
  return '"'.repeat(Math.max(3, max + 1));
}

// Deterministic: same snapshots in, same bytes out. `rooms` entries carry the exact
// compiled JSON text; the const value must equal it byte for byte (raw string rule:
// the value is everything between the newline after the opening delimiter and the
// newline before the closing one, so emit exactly one extra newline after the text).
export function genRoomsCs(modName: string, rooms: { name: string; text: string }[]): string {
  const L: string[] = [
    "// GENERATED by stoneshard-room-editor from rooms/*.compiled.json -- do not edit by hand.",
    "// The editor rewrites this file whenever it disagrees with the compiled snapshots",
    "// (server start, svre compile/import/adopt).",
    "using ModShardLauncher;",
    "",
    `namespace ${modName};`,
    "",
    "public static class SvGeneratedRooms",
    "{",
    "    // Call after SvGeneratedAssets.Register() and after every Msl.AddCode whose name a",
    "    // room references as creation_code (RoomUtils resolves both by name, silently).",
    "    public static void Register()",
    "    {",
  ];
  for (const r of [...rooms].sort((a, b) => a.name.localeCompare(b.name)))
    L.push(`        Msl.AddRoomJson(${r.name});`);
  L.push("    }");
  for (const r of [...rooms].sort((a, b) => a.name.localeCompare(b.name))) {
    const q = delimiterFor(r.text);
    // the join below adds exactly one \n after the text (and after the opening
    // delimiter), so the const's value is `text` byte for byte whether or not it
    // ends in a newline; the closing delimiter sits at column 0 -> no stripping
    L.push("", `    public const string ${r.name} = ${q}`, r.text, `${q};`);
  }
  L.push("}", "");
  return L.join("\n");
}

// Rewrite <Mod>.Rooms.g.cs when it disagrees with the given snapshots. Returns the room
// names that went in and whether the file was (re)written. Rooms whose name is not a
// valid C# identifier are skipped (createRoom/importRoom already enforce r_* names).
export function syncRoomsCs(modDir: string, rooms: { name: string; text: string }[]): { synced: boolean; rooms: string[] } {
  const usable = rooms.filter((r) => /^[A-Za-z_]\w*$/.test(r.name));
  const out = roomsCsPath(modDir);
  // don't litter a Rooms.g.cs into a mod that has no room pipeline at all -- unless one
  // is already there (then keep healing it, even back to empty)
  if (!usable.length && !fs.existsSync(out) && !fs.existsSync(path.join(modDir, "rooms")))
    return { synced: false, rooms: [] };
  const text = genRoomsCs(path.basename(modDir), usable);
  const cur = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : null;
  if (cur === text) return { synced: false, rooms: usable.map((r) => r.name) };
  fs.writeFileSync(`${out}.tmp`, text);
  fs.renameSync(`${out}.tmp`, out);
  return { synced: true, rooms: usable.map((r) => r.name) };
}
